apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zookeeper