apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: deployment-busybox
      name: busybox-deploy-pod 
    spec:
      containers:
      - name: busybox
        image: busybox
        tty: true
        stdin: true
        args:
        - sleep
        - "1000000"
        ports:
        - containerPort: 80
