kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:  
  name: secret-reader # "namespace" omitted since ClusterRoles are not namespaced
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
