apiVersion: v1
kind: Service
metadata:
  name: externalipnginx-service
  labels:
    run: externalipnginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: deployment-nginx
  externalIPs: [10.239.151.98, 10.239.151.93]
