apiVersion: v1
kind: Service
metadata:
  name: nginx-svr-loadbalance
  labels:
    loadbalance-svr: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
