apiVersion: v1
kind: Service
metadata:
  name: nodeportnginx-service
  labels:
    run: nodeportnginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30061
    protocol: TCP
  selector:
    app: nginx
