apiVersion: v1
kind: Service
metadata:
  name: publicipnginx-service
  labels:
    run: publicipnginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
  publicIPs:
  - 192.168.1.133
