apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/allen/temp/data
