version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - 'kafka1_data:/bitnami'
    depends_on:
      - zookeeper
  kafka2:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - 'kafka2_data:/bitnami'
    depends_on:
      - zookeeper
  kafka3:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9095:9095'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://localhost:9095
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - 'kafka3_data:/bitnami'
    depends_on:
      - zookeeper
  influxdb:
    image: influxdb:1.8.3
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=intel_123
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=intel_123
      - INFLUXDB_DB=my_database
  chronograf:
    image: chronograf:1.8.8
    ports:
      - '8888:8888'
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=user
      - INFLUXDB_PASSWORD=intel_123
  grafana:
    image: grafana/grafana:7.3.3
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=intel_123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - ../grafana-provisioning/:/etc/grafana/provisioning

volumes:
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local
  influxdb_data:
    driver: local
  chronograf_data:
    driver: local
  grafana_data:
    driver: local