#https://github.com/ibm-cloud-architecture/refarch-eda/blob/master/deployments/kafka/prod/kafka-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  selector:
    matchLabels:
      app: kafka
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - kafka
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - zookeeper
                topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 300
      containers:
        - name: k8skafka
          imagePullPolicy: IfNotPresent
          image: bitnami/kafka:2.6.0
          resources:
            requests:
              memory: "2Gi"
              cpu: 2000m
          ports:
            - containerPort: 9092
              name: server
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value : "zookeeper-0.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.default.svc.cluster.local:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/kafka
      volumes:
        - emptyDir: { }
          name: datadir
      securityContext:
        runAsUser: 1000
        fsGroup: 1000