docker volume rm cluster_chronograf_data cluster_grafana_data cluster_influxdb_data cluster_kafka1_data cluster_kafka2_data cluster_kafka3_data
docker volume rm single-node_grafana_data single-node_kafka_data
