apiVersion: v1
kind: Pod
metadata:
  name: allen-busybox
  labels:
    app: busybox-app
spec:
  containers:
    - name: busybox-con
      image: busybox
      args:
        - sleep
        - "1000000"
      ports:
        - containerPort: 80
